site_name: My Course
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - Lessons:
      - Lesson 1: lessons/lesson1.md
      - Lesson 2: lessons/lesson2.md
  - Exercises:
      - Exercise 1: exercises/exercise1.md
      - Exercise 2: exercises/exercise2.md
